[[artifact]]
name = "claude-code-plugin"

[[artifact.step]]
from = "agent-plugins/claude-code"
to = ""

[[artifact.step]]
from = "agent-plugins/symposium.sh"
to = "scripts/symposium.sh"

[[artifact.step]]
from = "skills/symposium"
to = "skills/symposium"

[[artifact.step]]
from = "agent-plugins/symposium.sh"
to = "skills/symposium/scripts/symposium.sh"
